apps/lots/urls.py
from django.urls import path

from . import views

app_name = "lots"
urlpatterns = [
    path("", views.LotListView.as_view(), name="list"),
    path("lot/create/", views.CreateLotView.as_view(), name="create"),
    path("lot/<int:pk>/update/", views.UpdateLotView.as_view(), name="update"),
    path("lot/<int:pk>/", views.DetailLotView.as_view(), name="details"),
    path("favorites/", views.FavoritesLotsView.as_view(), name="favorites"),
    path(
        "lot/<int:pk>/favorite/",
        views.FavoritesLotActionView.as_view(),
        name="action_favorites_lot",
    ),
]

apps/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views

app_name = "users"
urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="users/login.html",
            next_page=reverse_lazy("lots:list"),
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="users/success.html",
            next_page=reverse_lazy("users:login"),
        ),
        name="logout",
    ),
    path(
        "change-password/",
        auth_views.PasswordChangeView.as_view(
            template_name="users/change_password.html",
            success_url=reverse_lazy("users:change-password-done"),
        ),
        name="change-password",
    ),
    path(
        "change-password/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="users/success.html",
        ),
        name="change-password-done",
    ),
    path(
        "reset-password/",
        auth_views.PasswordResetView.as_view(
            template_name="users/reset_password.html",
            email_template_name="users/emails/password_reset.html",
            success_url=reverse_lazy("users:reset-password-send"),
        ),
        name="reset-password",
    ),
    path(
        "reset-password/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/success.html",
        ),
        name="reset-password-send",
    ),
    path(
        "reset/token-<uidb64>-<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/reset_password_complete.html",
            success_url=reverse_lazy("users:reset-password-done"),
        ),
        name="reset-password-confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/success.html",
        ),
        name="reset-password-done",
    ),
    path(
        "registration/",
        views.RegistrationView.as_view(),
        name="registration",
    ),
    path(
        "profile/<int:pk>/",
        views.UserDetailView.as_view(),
        name="profile",
    ),
    path(
        "profile/edit/",
        views.UserEditView.as_view(),
        name="profile-edit",
    ),
]

templates/includes/list.html
{% load i18n %}
<div class="d-flex flex-column">
  <div class="row mt-2 mb-2">
    <div class="col-3">
      <select id="order" class="form-select">
        <option name="order" value="">{% trans "Select method of sort" %}</option>
        <option name="order" value="start_price">{% trans "On cost up" %}</option>
        <option name="order" value="-start_price">{% trans "On cost down" %}</option>
        <option name="order" value="name">{% trans "On naming up" %}</option>
        <option name="order" value="-name">{% trans "On naming down" %}</option>
      </select>
    </div>
    <div class="col-3">
      <select id="status" class="form-select">
        <option name="status" value="" selected>{% trans "Select method of filter by status" %}</option>
        <option name="status" value="FINISHED">{% trans "Finished" %}</option>
        <option name="status" value="IN_PROCCESS">{% trans "In proccess" %}</option>
      </select>
    </div>
  </div>
  
  <div class="row">
    {% if lots %}
      {% for item in lots %}
          <div class="card my-3 col-3">
            <a href="{% url 'lots:details' item.pk %}">
              <img src="{{ item.images.first.image.url }}" class="card-img-top">
            </a>
            <div class="card-body">
              <a href="{% url 'lots:details' item.pk %}" class="text-decoration-none text-dark">
                <h5 class="card-title">{{ item.name }}</h5>
              </a>
              <p class="card-text">{{ item.description }}</p>
              <a href="{% url 'lots:details' item.pk %}" class="btn btn-primary">{% trans "Buy" %}</a>
              <h5>{{ item.start_price }}</h5>
            </div>
          </div>
      {% endfor %}
    {% else %}
        <p>{% trans "Nothing found" %}</p>
    {% endif %}
  </div>
  <nav>
    <ul class="pagination">
      {% if is_paginated %}
        {% if page_obj.has_previous %}
        <li class="page-item">
            <button class="page-link prev-arrow" data-page="{{ page_obj.previous_page_number }}">
              <span aria-hidden="true">&laquo;</span>
            </button>
        </li>
        <li class="page-item">
          <button class="page-link prev-page" data-page="{{ page_obj.previous_page_number }}">
            {{ page_obj.previous_page_number }}
          </button>
        </li>
        {% endif %}

        <li class="page-item active">
          <button class="page-link" data-page="{{ page_obj.number }}">
            {{ page_obj.number }}
          </button>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <button class="page-link next-page" data-page="{{ page_obj.next_page_number }}">
            {{ page_obj.next_page_number }}
          </button>
        </li>
        <li class="page-item">
          <button class="page-link next-arrow" data-page="{{ page_obj.next_page_number }}">
            <span aria-hidden="true">&raquo;</span>
          </button>
        </li>
        {% endif %}
      {% endif %}
    </ul>
  </nav>
</div>

templates/includes/navigation.html
{% load static %}
{% load i18n %}
  <header class="header-main">
    <nav class="container navbar navbar-main bg-white border-radius-xl py-2" data-lots-list-url="{% url 'lots:list' %}">
      <div class="col-12 row ms-auto mb-2">
        <div class="col-3">
            <a class="navbar-brand" href="{% url 'lots:list' %}">IBidThese</a>
        </div>
        <div class="col-6 align-items-center">
          <div class="bg-white row">
            <form class="d-flex search border-radius-lg d-flex me-2 col-9" method="GET" action="{% url 'lots:list' %}">
              <input name="search" type="text" class="form-control border-0 ps-3" placeholder="Type here...">
              <button type="submit" class="btn bg-gradient-primary my-1 me-1 ms-2">{% trans "Search" %}</button>
            </form>
            <div class="row col-3 col-3">
              <div class="col-auto ms-auto">
                <div class="dropdown">
                  <a class="cursor-pointer" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{% static 'bell.png' %}" height="32px" alt="{% trans 'Bell' %}">
                  </a>
                  <ul class="dropdown-menu dropdown-menu-right px-2 py-3 ms-n4" aria-labelledby="dropdownMenuButton">
                    <li>...</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 row mx-auto p-1">
        <div class="col">
          <select id="category" class="form-select border-0 p-0">
            <option class="text-center" value="" selected>{% trans "Categories" %}</option>
            {% for category in categories %}
               <option class="text-center" name="category" value="{{ category.name }}">{% trans category.name %}</option>
            {% endfor %}
          </select>
        </div>
        <div class="col text-center">
          <a href="{% url "lots:favorites" %}">{% trans "Favorites" %}</a>
        </div>
        <div class="col text-center">
          <a href="">{% trans "Newly Listed" %}</a>
        </div>
        <div class="col text-center">
          <div class="col dropdown d-inline">
            <a class="cursor-pointer" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
              <p>
                {% if request.user.is_authenticated %}
                  {% trans "Hi" %}, {% if user.first_name %}{{ user.first_name }}{% else %}Username{% endif %}
                {% else %}
                  {% trans "My profile" %}
                {% endif %}
              </p>
            </a>
            <ul class="dropdown-menu dropdown-menu-right px-2 py-3 ms-n4" aria-labelledby="dropdownMenuButton">
              {% if request.user.is_authenticated %}
                <a href="{% url 'users:profile' request.user.pk %}">
                  <li>
                    {% trans "Profile" %}
                  </li>
                </a>
              {% endif %}
              <a href="{% url 'users:profile-edit' %}">
                <li>
                  {% trans "Profile settings" %}
                </li>
              </a>
                {% if request.user.is_authenticated %}
                  <a href="{% url 'users:logout' %}">
                    <li>
                      {% trans "Logout" %}
                    </li>
                  </a>
                {% else %}
                  <a href="{% url 'users:login' %}">
                    <li>
                      {% trans "Login" %}
                    </li>
                  </a>
                {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </header>

templates/includes/scripts.html
{% load static %}

  <!--   Core JS Files   -->
  <script src="{% static 'popper.min.js' %}"></script>
  <script src="{% static 'bootstrap.min.js' %}"></script>
  <script src="{% static 'smooth-scrollbar.min.js' %}"></script>

  <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'soft-ui-dashboard.js' %}"></script>

  <!-- Specific JS files for all-->
  <script src="{% static 'script.js' %}"></script>