apps/lots/urls.py
from django.urls import path

from . import views

app_name = "lots"
urlpatterns = [
    path("", views.LotListView.as_view(), name="list"),
    path("lot/create/", views.CreateLotView.as_view(), name="create"),
    path("lot/<int:pk>/update/", views.UpdateLotView.as_view(), name="update"),
    path("lot/<int:pk>/", views.DetailLotView.as_view(), name="details"),
    path("favorites/", views.FavoritesLotsView.as_view(), name="favorites"),
    path(
        "lot/<int:pk>/favorite/",
        views.FavoritesLotActionView.as_view(),
        name="action_favorites_lot",
    ),
]

apps/lots/models/bid.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.core.fields import PriceField
from apps.core.models import BaseModel


class Bid(BaseModel):
    """Model for bid per lot."""

    bid = PriceField(
        verbose_name=_("Bid"),
    )
    lot = models.ForeignKey(
        "lots.Lot",
        on_delete=models.CASCADE,
        related_name="bids",
    )
    user = models.ForeignKey(
        "users.User",
        on_delete=models.CASCADE,
        related_name="bids",
    )

    def __str__(self) -> str:
        return f"Bid {self.bid} of {self.lot.name} lot"

    class Meta:
        verbose_name_plural = _("Bids")
        verbose_name = _("Bid")

apps/lots/models/lot.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

import arrow

from apps.core.fields import PriceField
from apps.core.models import BaseModel


class Lot(BaseModel):
    """Model for lot.

    Lot statuses:
        Finished: lot in closed and read-only
        In Proccess: lot in active
        Draft: lot not created
    """

    class Status(models.TextChoices):
        """Class choices."""

        FINISHED = "FINISHED", _("Finished")
        IN_PROCCESS = "IN_PROCCESS", _("In Proccess")
        DRAFT = "DRAFT", _("Draft")

    user = models.ForeignKey(
        "users.User",
        on_delete=models.CASCADE,
        related_name="lot",
    )
    name = models.CharField(
        max_length=256,
        verbose_name=_("Name"),
    )
    description = models.TextField(
        verbose_name=_("Description"),
    )
    interest_users = models.ManyToManyField(
        "users.User",
        related_name="favorite_lots",
    )
    category = models.ForeignKey(
        "Category",
        on_delete=models.CASCADE,
        verbose_name=_("Category"),
        related_name="lots",
    )
    start_price = PriceField(
        verbose_name=_("Start price"),
    )
    bid_increment = PriceField(
        verbose_name=_("Bid increment"),
        validators=[
            MinValueValidator(1.0),
        ],
        help_text=_("Different between last and current bids"),
    )
    redemption_price = PriceField(
        verbose_name=_("Redemption price"),
        null=True,
        blank=True,
    )
    status = models.CharField(
        max_length=11,
        verbose_name=_("Status"),
        choices=Status.choices,
        default=Status.DRAFT,
    )
    end_date = models.DateTimeField(
        verbose_name=_("Time end of bid"),
    )

    def __str__(self) -> str:
        return self.name

    def clean_end_date(self):
        """Method for validate end date of lot."""
        if arrow.utcnow() >= self.end_date:
            raise ValidationError(
                _("End date can't be earlier that now"),
            )

    def clean_redemption_price(self):
        """Method for validate redemption price of lot."""
        if not self.redemption_price:
            return
        if self.redemption_price < self.start_price:
            raise ValidationError(
                _("Redemption price can not be less then start price"),
            )

    class Meta:
        verbose_name_plural = _("Lots")
        verbose_name = _("Lot")


class Category(BaseModel):
    """Model for Category."""

    name = models.CharField(
        max_length=32,
        verbose_name=_("Name"),
        unique=True,
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = _("Categories")
        verbose_name = _("Category")


class LotImage(BaseModel):
    """Model for lot image."""

    lot = models.ForeignKey(
        Lot,
        on_delete=models.CASCADE,
        verbose_name=_("Image of lot"),
        related_name="images",
    )
    image = models.ImageField(
        upload_to=settings.DEFAULT_MEDIA_PATH,
    )

    class Meta:
        verbose_name_plural = _("Images")
        verbose_name = _("Image")

apps/lots/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from apps.lots import models


class LotCreateForm(forms.ModelForm):
    """Form for create lot."""

    class Meta:
        model = models.Lot
        fields = (
            "name",
            "description",
            "start_price",
            "bid_increment",
            "redemption_price",
            "status",
            "end_date",
            "category",
        )
        widgets = {
            "end_date": forms.TextInput(
                attrs={
                    "type": "datetime-local",
                },
            ),
        }


class LotImageForm(forms.ModelForm):
    """Form for one image of lot."""

    class Meta:
        model = models.LotImage
        fields = (
            "image",
        )


ImageLotFormSet = forms.inlineformset_factory(
    models.Lot,
    models.LotImage,
    form=LotImageForm,
    max_num=10,
    can_delete=True,
    extra=1,
)


class BidCreateForm(forms.ModelForm):
    """Form for create bid."""

    def __init__(self, lot, *args, **kwargs):
        """Override to store lot instance."""
        super().__init__(*args, **kwargs)
        self.lot = lot

    def clean_bid(self):
        """Validate price of bid more than start price or last bid."""
        last_bid = models.Bid.objects.filter(
            lot=self.lot,
        ).order_by("-created").first()
        min_expected_price = self.lot.start_price
        if last_bid:
            min_expected_price = last_bid.bid + self.lot.bid_increment
        if self.lot.start_price >= self.cleaned_data["bid"]:
            raise forms.ValidationError(
                _("Start price can not be more or equal than bid price"),
            )
        if self.cleaned_data["bid"] <= min_expected_price:
            raise forms.ValidationError(
                _(
                    "Current bid can not be less or equal, "
                    f"than previous bid ({min_expected_price})",
                ),
            )
        return self.cleaned_data["bid"]

    class Meta:
        model = models.Bid
        fields = (
            "bid",
        )

apps/lots/views.py
from typing import Any, Optional

from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)
from django.db.models import Q, QuerySet
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import View, generic

from apps.lots import forms

from . import models


class FavoritesLotActionView(LoginRequiredMixin, generic.edit.FormMixin, View):
    """Actions with favorite lots."""

    def get_success_url(self):
        """Get url to lot detail page after add lot in favorites."""
        return reverse("lots:details", kwargs={"pk": self.kwargs["pk"]})

    def post(self, request, *args, **kwargs) -> HttpResponseRedirect:
        """Handle POST requests.

        After request, lot remove or add (depending on the previous state)
        from set of favorite lots of user.
        """
        lot = get_object_or_404(models.Lot, id=self.kwargs["pk"])
        if lot in self.request.user.favorite_lots.all():
            self.request.user.favorite_lots.remove(lot)
        else:
            self.request.user.favorite_lots.add(lot)
        return redirect(self.get_success_url())


class BaseLotListView(generic.list.ListView):
    """BaseList view for Lots."""

    paginate_by = 8
    context_object_name = "lots"
    queryset = models.Lot.objects.exclude(status=models.Lot.Status.DRAFT)
    ordering_fields = [
        "start_price",
        "name",
    ]

    def get_context_data(self, **kwargs) -> dict:
        """Get categories list."""
        data = super().get_context_data(**kwargs)
        data["categories"] = models.Category.objects.all()
        return data

    def search_queryset(self, object_list) -> QuerySet:
        """Get queryset with search query."""
        query_search = self.request.GET.get("search")
        if query_search:
            return object_list.filter(
                    Q(name__icontains=query_search) |
                    Q(description__icontains=query_search),
            )
        return object_list

    def order_queryset(self, object_list) -> QuerySet:
        """Get ordered queryset."""
        query_order = self.request.GET.get("order")
        if query_order:
            field = self.get_ordering()
            if field:
                return object_list.order_by(field)
        return object_list

    def filter_queryset_category(self, object_list) -> QuerySet:
        """Get filtered queryset."""
        query_filter = self.request.GET.get("category")
        if query_filter:
            category_name = get_object_or_404(
                models.Category,
                name=query_filter,
            )
            return object_list.filter(category=category_name)
        return object_list

    def filter_queryset_status(self, object_list) -> QuerySet:
        """Get filtered queryset."""
        query_filter = self.request.GET.get("status")
        if query_filter:
            return object_list.filter(status=query_filter)
        return object_list

    def get_ordering(self) -> Optional[str]:
        """Get key for ordering queryset."""
        query_order = self.request.GET.get("order")
        if query_order.lstrip("-") in self.ordering_fields:
            return query_order
        return None

    def get_queryset(self) -> QuerySet:   # pylint: disable=arguments-differ
        """Get search result."""
        object_list = self.queryset
        object_list = self.search_queryset(object_list)
        object_list = self.order_queryset(object_list)
        object_list = self.filter_queryset_category(object_list)
        object_list = self.filter_queryset_status(object_list)
        return object_list


class LotListView(BaseLotListView):
    """List view for Lots."""

    template_name = "lots/list_lots.html"


class FavoritesLotsView(LoginRequiredMixin, BaseLotListView):
    """List view for favorites Lots of current user."""

    template_name = "lots/favorites_lots.html"

    def get_queryset(self) -> QuerySet:  # pylint: disable=arguments-differ
        """Get favorites lots of user."""
        return super().get_queryset().filter(
            id__in=self.request.user.favorite_lots.values("id"),
        )


class UpdateLotView(PermissionRequiredMixin, generic.edit.UpdateView):
    """View for Lot update."""

    template_name = "lots/lot_update_form.html"
    form_class = forms.LotCreateForm
    model = models.Lot
    queryset = models.Lot.objects.all()

    def get_success_url(self) -> str:
        """Get url to lot detail page after bid creation."""
        return reverse_lazy(
            "lots:details",
            kwargs={"pk": self.get_object().pk},
        )

    def has_permission(self) -> bool:
        """Only owner can edit lot."""
        return all([
            self.request.user.id == self.get_object().user.id,
            self.get_object().status == "DRAFT",
        ])

    def get_context_data(self, **kwargs):
        """Get context for page."""
        self.object = (  # pylint: disable=attribute-defined-outside-init
            self.get_object()
        )
        context = super().get_context_data(**kwargs)
        context["form"].fields["status"].choices = [
            ("IN_PROCCESS", _("In Proccess")),
            ("DRAFT", _("Draft")),
        ]
        context["lot_images_formset"] = forms.ImageLotFormSet(
            instance=self.object,
        )
        return context

    def post(self, request, *args, **kwargs):
        """Handle POST requests."""
        form = forms.LotCreateForm(
            request.POST,
            instance=self.get_object(),
        )
        lot_images_formset = forms.ImageLotFormSet(
            request.POST,
            request.FILES,
            instance=self.get_object(),
        )
        if form.is_valid() and lot_images_formset.is_valid():
            return self.form_valid(form, lot_images_formset)
        return self.form_invalid(form, lot_images_formset)

    def form_valid(
        self,
        form,
        lot_images_formset,
    ):  # pylint: disable=arguments-differ
        """Overridden for save form and formset when update lot."""
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        lot_images_formset.instance = obj
        lot_images_formset.save()
        return redirect(self.get_success_url())

    def form_invalid(
        self,
        form,
        lot_images_formset,
    ):  # pylint: disable=arguments-differ
        """Overridden for reload context for retry update load."""
        return self.render_to_response(
            self.get_context_data(
                form=form,
                lot_images_formset=lot_images_formset,
            ),
        )


class CreateLotView(PermissionRequiredMixin, generic.edit.FormView):
    """View for Lot create."""

    template_name = "lots/lot_create_form.html"
    form_class = forms.LotCreateForm

    def get_success_url(self) -> str:
        """Get url to lot detail page after bid creation."""
        return reverse_lazy("lots:details", kwargs={"pk": self.object.pk})

    def has_permission(self) -> bool:
        """Only owner can edit lot."""
        return self.request.user.can_create_lots

    def get_context_data(self, **kwargs):
        """Get context for page."""
        context = super().get_context_data(**kwargs)
        context["form"].fields["status"].choices = [
            ("IN_PROCCESS", _("In Proccess")),
            ("DRAFT", _("Draft")),
        ]
        context["lot_images_formset"] = forms.ImageLotFormSet()
        return context

    def post(self, request, *args, **kwargs):
        """Handle POST requests."""
        self.object = None  # pylint: disable=attribute-defined-outside-init
        form = self.get_form()
        lot_images_formset = forms.ImageLotFormSet(
            data=request.POST,
            files=request.FILES,
        )
        if form.is_valid() and lot_images_formset.is_valid():
            return self.form_valid(form, lot_images_formset)
        return self.form_invalid(form, lot_images_formset)

    def form_valid(
        self,
        form,
        lot_images_formset,
    ):  # pylint: disable=arguments-differ
        """Overridden for save form and formset when creating lot."""
        self.object = (  # pylint: disable=attribute-defined-outside-init
            form.save(commit=False)
        )
        self.object.user = self.request.user
        self.object.save()
        lot_images_formset.instance = self.object
        lot_images_formset.save()
        return redirect(self.get_success_url())

    def form_invalid(
        self,
        form,
        lot_images_formset,
    ):  # pylint: disable=arguments-differ
        """Overridden for reload context for retry create load."""
        return self.render_to_response(
            self.get_context_data(
                form=form,
                lot_images_formset=lot_images_formset,
            ),
        )


class DetailLotView(
    PermissionRequiredMixin,
    generic.DetailView,
    generic.edit.FormMixin,
):
    """View for Lot details."""

    model = models.Lot
    template_name = "lots/lot.html"
    context_object_name = "lot"
    form_class = forms.BidCreateForm

    def has_permission(self) -> bool:
        """Solve, get user special permissions or not."""
        obj = self.get_object()
        return any([
            obj.status != "DRAFT",
            self.request.user == obj.user,
        ])

    def handle_no_permission(self) -> HttpResponseRedirect:

templates/lots/favorites_lots.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Favorites lots" %}{% endblock %}

{% block content %}
    {% include "includes/list.html" %}
{% endblock %}



templates/lots/list_lots.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Lots" %}{% endblock %}

{% block content %}
    {% include "includes/list.html" %}
{% endblock %}

templates/lots/lot.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{{ lot.name }}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
{% endblock %}

{% block content %}
    <div class="main py-2">
        <div class="row">
            <div id="carouselIndicators" class="carousel slide col-5" data-bs-ride="carousel">
                <div class="carousel-inner col-4">
                    {% for image in lot.images.all %}
                        <div class="carousel-item {% if forloop.first %} active {% endif %}">
                            <img src="{{ image.image.url }}" class="d-block w-100">
                        </div>
                    {% endfor %}
                </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselIndicators" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselIndicators" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
            <div class="info col-7">
                <h5>{% trans lot.name %}</h5>
                <p>{% trans "Description" %}: {% trans lot.description %}</p>
                <p>{% trans "User" %}: {{ lot.user.full_name }}</p>
                <p>{% trans "Start price" %}: {{ lot.start_price }}</p>
                <p>{% trans "Redemption price:" %} {{ lot.redemption_price }}</p>
                <p>{% trans "Status" %}: {{ lot.get_status_display }}</p>
                <p>{% trans "Ending" %}: {{ lot.end_date }}</p>
            </div>
        </div>
        <form action="{% url 'lots:action_favorites_lot' lot.pk %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn fs-6 bi bi-star{% if lot in user.favorite_lots.all %}-fill{% endif %}"></button>
        </form>
        <div>
            {% if user.id != lot.user.id %}
                <form action="{% url 'lots:details' lot.pk %}" method="post" class="col-5 my-3">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn" type="submit">{% trans "Add bid" %}</button>
                </form>
            {% endif %}
            <ul class="list-group">
                {% for bid in lot.bids.all|dictsortreversed:"created" %}
                    <li class="list-group-item">{% trans "Bid of " %}<span class="fw-bold">{{ bid.user }}</span>{% trans " with " %}<span class="fw-bold">{{ bid.bid }}</span></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/lots/lot_create_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title%}{% trans "Create Lot" %}{% endblock %}

{% block content %}
    <form action="{% url 'lots:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token%}
        {{ form|crispy }}
        <div class="row">
            {{ lot_images_formset.non_form_errors }}
            {{ lot_images_formset.management_form }}
            {% for image in lot_images_formset %}
                <div class="my-1 {{ lot_images_formset.prefix }} formset_row">
                    <div class="col ml-4">{{ image.DELETE }}</div>
                    {{ image.image }}
                </div>
            {% endfor %}
        </div>
        <button class="btn" type="submit">{% trans "Add Lot" %}</button>
    </form>
{% endblock %}

{% block javascripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $('.formset_row').formset({
            prefix: '{{ lot_images_formset.prefix }}',
            addText: 'Add image',
            deleteText: 'Delete',
            addCssClass: 'add-row my-1', 
        });
    </script>
{% endblock %}

templates/lots/lot_update_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title%}{% trans "Update Lot" %}{% endblock %}

{% block content %}
    <form action="{% url 'lots:update' lot.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token%}
        {{ form|crispy }}
        <div class="row">
            {{ lot_images_formset.non_form_errors }}
            {{ lot_images_formset.management_form }}
            {% for image in lot_images_formset %}
                {{ image.id }}
                {% if image.instance.id %}
                    <div class="my-1 {{ lot_images_formset.prefix }} formset_row">
                        <div class="col ml-4">{{ image.DELETE }}</div>
                        {{ image.instance.image }}
                    </div>
                {% else %}
                    <div class="my-1 {{ lot_images_formset.prefix }} formset_row">
                        <div class="col ml-4">{{ image.DELETE }}</div>
                        {{ image.image }}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <button class="btn" type="submit">{% trans "Update Lot" %}</button>
    </form>
{% endblock %}

{% block javascripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $('.formset_row').formset({
            prefix: '{{ lot_images_formset.prefix }}',
            addText: 'Add image',
            deleteText: 'Delete',
            addCssClass: 'add-row my-1', 
        });
    </script>
{% endblock %}