apps/lots/urls.py
from django.urls import path

from . import views

app_name = "lots"
urlpatterns = [
    path("", views.LotListView.as_view(), name="list"),
    path("lot/create/", views.CreateLotView.as_view(), name="create"),
    path("lot/<int:pk>/update/", views.UpdateLotView.as_view(), name="update"),
    path("lot/<int:pk>/", views.DetailLotView.as_view(), name="details"),
    path("favorites/", views.FavoritesLotsView.as_view(), name="favorites"),
    path(
        "lot/<int:pk>/favorite/",
        views.FavoritesLotActionView.as_view(),
        name="action_favorites_lot",
    ),
]

apps/users/api/auth/urls.py
from django.urls import path

from knox import views as knox_views

from . import views

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", knox_views.LogoutView.as_view(), name="logout"),
    path(
        "logout-all/", knox_views.LogoutAllView.as_view(),
        name="logout_all",
    ),
    path(
        "password-reset/", views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password-reset-confirm/", views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
]

apps/users/api/urls.py
from rest_framework.routers import DefaultRouter

from . import views

# router.register(r"users", UsersAPIView)
router = DefaultRouter()
router.register(r"", views.UsersViewSet, basename="user")
urlpatterns = router.urls

apps/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views

app_name = "users"
urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="users/login.html",
            next_page=reverse_lazy("lots:list"),
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="users/success.html",
            next_page=reverse_lazy("users:login"),
        ),
        name="logout",
    ),
    path(
        "change-password/",
        auth_views.PasswordChangeView.as_view(
            template_name="users/change_password.html",
            success_url=reverse_lazy("users:change-password-done"),
        ),
        name="change-password",
    ),
    path(
        "change-password/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="users/success.html",
        ),
        name="change-password-done",
    ),
    path(
        "reset-password/",
        auth_views.PasswordResetView.as_view(
            template_name="users/reset_password.html",
            email_template_name="users/emails/password_reset.html",
            success_url=reverse_lazy("users:reset-password-send"),
        ),
        name="reset-password",
    ),
    path(
        "reset-password/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/success.html",
        ),
        name="reset-password-send",
    ),
    path(
        "reset/token-<uidb64>-<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/reset_password_complete.html",
            success_url=reverse_lazy("users:reset-password-done"),
        ),
        name="reset-password-confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/success.html",
        ),
        name="reset-password-done",
    ),
    path(
        "registration/",
        views.RegistrationView.as_view(),
        name="registration",
    ),
    path(
        "profile/<int:pk>/",
        views.UserDetailView.as_view(),
        name="profile",
    ),
    path(
        "profile/edit/",
        views.UserEditView.as_view(),
        name="profile-edit",
    ),
]

apps/users/forms.py

from django.contrib.auth.forms import UserCreationForm
from django.forms import Textarea, TextInput
from django.forms.models import ModelForm

from . import models


class RegistrationForm(UserCreationForm):
    """Form for user registration."""

    class Meta:
        model = models.User
        fields = [
            "email",
            "password1",
            "password2",
            "first_name",
            "last_name",
            "avatar",
            "birthday",
            "contact_info",
        ]
        widgets = {
            "contact_info": Textarea(attrs={"cols": 60, "rows": 4}),
            "birthday": TextInput(attrs={"type": "date"}),
        }


class UserEditForm(ModelForm):
    """Form for editing user information."""

    class Meta:
        model = models.User
        fields = [
            "first_name",
            "last_name",
            "avatar",
            "birthday",
            "contact_info",
        ]
        widgets = {
            "contact_info": Textarea(attrs={"cols": 60, "rows": 4}),
            "birthday": TextInput(attrs={"type": "date"}),
        }

apps/lots/views.py
from typing import Any, Optional

from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)
from django.db.models import Q, QuerySet
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import View, generic

from apps.lots import forms

from . import models


class FavoritesLotActionView(LoginRequiredMixin, generic.edit.FormMixin, View):
    """Actions with favorite lots."""

    def get_success_url(self):
        """Get url to lot detail page after add lot in favorites."""
        return reverse("lots:details", kwargs={"pk": self.kwargs["pk"]})

    def post(self, request, *args, **kwargs) -> HttpResponseRedirect:
        """Handle POST requests.

        After request, lot remove or add (depending on the previous state)
        from set of favorite lots of user.
        """
        lot = get_object_or_404(models.Lot, id=self.kwargs["pk"])
        if lot in self.request.user.favorite_lots.all():
            self.request.user.favorite_lots.remove(lot)
        else:
            self.request.user.favorite_lots.add(lot)
        return redirect(self.get_success_url())


class BaseLotListView(generic.list.ListView):
    """BaseList view for Lots."""

    paginate_by = 8
    context_object_name = "lots"
    queryset = models.Lot.objects.exclude(status=models.Lot.Status.DRAFT)
    ordering_fields = [
        "start_price",
        "name",
    ]

    def get_context_data(self, **kwargs) -> dict:
        """Get categories list."""
        data = super().get_context_data(**kwargs)
        data["categories"] = models.Category.objects.all()
        return data

    def search_queryset(self, object_list) -> QuerySet:
        """Get queryset with search query."""
        query_search = self.request.GET.get("search")
        if query_search:
            return object_list.filter(
                    Q(name__icontains=query_search) |
                    Q(description__icontains=query_search),
            )
        return object_list

    def order_queryset(self, object_list) -> QuerySet:
        """Get ordered queryset."""
        query_order = self.request.GET.get("order")
        if query_order:
            field = self.get_ordering()
            if field:
                return object_list.order_by(field)
        return object_list

    def filter_queryset_category(self, object_list) -> QuerySet:
        """Get filtered queryset."""
        query_filter = self.request.GET.get("category")
        if query_filter:
            category_name = get_object_or_404(
                models.Category,
                name=query_filter,
            )
            return object_list.filter(category=category_name)
        return object_list

    def filter_queryset_status(self, object_list) -> QuerySet:
        """Get filtered queryset."""
        query_filter = self.request.GET.get("status")
        if query_filter:
            return object_list.filter(status=query_filter)
        return object_list

    def get_ordering(self) -> Optional[str]:
        """Get key for ordering queryset."""
        query_order = self.request.GET.get("order")
        if query_order.lstrip("-") in self.ordering_fields:
            return query_order
        return None

    def get_queryset(self) -> QuerySet:   # pylint: disable=arguments-differ
        """Get search result."""
        object_list = self.queryset
        object_list = self.search_queryset(object_list)
        object_list = self.order_queryset(object_list)
        object_list = self.filter_queryset_category(object_list)
        object_list = self.filter_queryset_status(object_list)
        return object_list


class LotListView(BaseLotListView):
    """List view for Lots."""

    template_name = "lots/list_lots.html"


class FavoritesLotsView(LoginRequiredMixin, BaseLotListView):
    """List view for favorites Lots of current user."""

    template_name = "lots/favorites_lots.html"

    def get_queryset(self) -> QuerySet:  # pylint: disable=arguments-differ
        """Get favorites lots of user."""
        return super().get_queryset().filter(
            id__in=self.request.user.favorite_lots.values("id"),
        )


class UpdateLotView(PermissionRequiredMixin, generic.edit.UpdateView):
    """View for Lot update."""

    template_name = "lots/lot_update_form.html"
    form_class = forms.LotCreateForm
    model = models.Lot
    queryset = models.Lot.objects.all()

    def get_success_url(self) -> str:
        """Get url to lot detail page after bid creation."""
        return reverse_lazy(
            "lots:details",
            kwargs={"pk": self.get_object().pk},
        )

    def has_permission(self) -> bool:
        """Only owner can edit lot."""
        return all([
            self.request.user.id == self.get_object().user.id,
            self.get_object().status == "DRAFT",
        ])

    def get_context_data(self, **kwargs):
        """Get context for page."""
        self.object = (  # pylint: disable=attribute-defined-outside-init
            self.get_object()
        )
        context = super().get_context_data(**kwargs)
        context["form"].fields["status"].choices = [
            ("IN_PROCCESS", _("In Proccess")),
            ("DRAFT", _("Draft")),
        ]
        context["lot_images_formset"] = forms.ImageLotFormSet(
            instance=self.object,
        )
        return context

    def post(self, request, *args, **kwargs):
        """Handle POST requests."""
        form = forms.LotCreateForm(
            request.POST,
            instance=self.get_object(),
        )
        lot_images_formset = forms.ImageLotFormSet(
            request.POST,
            request.FILES,
            instance=self.get_object(),
        )
        if form.is_valid() and lot_images_formset.is_valid():
            return self.form_valid(form, lot_images_formset)
        return self.form_invalid(form, lot_images_formset)

    def form_valid(
        self,
        form,
        lot_images_formset,
    ):  # pylint: disable=arguments-differ
        """Overridden for save form and formset when update lot."""
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        lot_images_formset.instance = obj
        lot_images_formset.save()
        return redirect(self.get_success_url())

    def form_invalid(
        self,
        form,
        lot_images_formset,
    ):  # pylint: disable=arguments-differ
        """Overridden for reload context for retry update load."""
        return self.render_to_response(
            self.get_context_data(
                form=form,
                lot_images_formset=lot_images_formset,
            ),
        )


class CreateLotView(PermissionRequiredMixin, generic.edit.FormView):
    """View for Lot create."""

    template_name = "lots/lot_create_form.html"
    form_class = forms.LotCreateForm

    def get_success_url(self) -> str:
        """Get url to lot detail page after bid creation."""
        return reverse_lazy("lots:details", kwargs={"pk": self.object.pk})

    def has_permission(self) -> bool:
        """Only owner can edit lot."""
        return self.request.user.can_create_lots

    def get_context_data(self, **kwargs):
        """Get context for page."""
        context = super().get_context_data(**kwargs)
        context["form"].fields["status"].choices = [
            ("IN_PROCCESS", _("In Proccess")),
            ("DRAFT", _("Draft")),
        ]
        context["lot_images_formset"] = forms.ImageLotFormSet()
        return context

    def post(self, request, *args, **kwargs):
        """Handle POST requests."""
        self.object = None  # pylint: disable=attribute-defined-outside-init
        form = self.get_form()
        lot_images_formset = forms.ImageLotFormSet(
            data=request.POST,
            files=request.FILES,
        )
        if form.is_valid() and lot_images_formset.is_valid():
            return self.form_valid(form, lot_images_formset)
        return self.form_invalid(form, lot_images_formset)

    def form_valid(
        self,
        form,
        lot_images_formset,
    ):  # pylint: disable=arguments-differ
        """Overridden for save form and formset when creating lot."""
        self.object = (  # pylint: disable=attribute-defined-outside-init
            form.save(commit=False)
        )
        self.object.user = self.request.user
        self.object.save()
        lot_images_formset.instance = self.object
        lot_images_formset.save()
        return redirect(self.get_success_url())

    def form_invalid(
        self,
        form,
        lot_images_formset,
    ):  # pylint: disable=arguments-differ
        """Overridden for reload context for retry create load."""
        return self.render_to_response(
            self.get_context_data(
                form=form,
                lot_images_formset=lot_images_formset,
            ),
        )


class DetailLotView(
    PermissionRequiredMixin,
    generic.DetailView,
    generic.edit.FormMixin,
):
    """View for Lot details."""

    model = models.Lot
    template_name = "lots/lot.html"
    context_object_name = "lot"
    form_class = forms.BidCreateForm

    def has_permission(self) -> bool:
        """Solve, get user special permissions or not."""
        obj = self.get_object()
        return any([
            obj.status != "DRAFT",
            self.request.user == obj.user,
        ])

    def handle_no_permission(self) -> HttpResponseRedirect:

apps/users/api/views.py
from django.contrib.auth import get_user_model

from rest_framework.permissions import AllowAny

from ...core.api.views import ReadOnlyViewSet
from . import serializers

User = get_user_model()


class UsersViewSet(ReadOnlyViewSet):
    """ViewSet for viewing accounts."""

    queryset = User.objects.all()
    serializer_class = serializers.UserSerializer
    base_permission_classes = (AllowAny,)

apps/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Prefetch
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView

from apps.lots.models import Bid

from . import forms, models


class RegistrationView(CreateView):
    """View for user registration."""

    template_name = "users/registration.html"
    form_class = forms.RegistrationForm
    success_url = reverse_lazy("users:login")


class UserDetailView(LoginRequiredMixin, DetailView):
    """View for user page with its lots and bids."""

    model = models.User
    template_name = "users/user_detail.html"
    context_object_name = "user"
    queryset = models.User.objects.prefetch_related(
        "lot__images",
        Prefetch(
            "bids",
            Bid.objects.order_by("-created").prefetch_related(
                Prefetch(
                    "lot__bids",
                    Bid.objects.order_by("-created"),
                ),
            ),
        ),
    )

    def get_context_data(self, **kwargs):
        """Get context for page."""
        context = super().get_context_data(**kwargs)
        context["lots"] = self.object.lot
        if self.request.user == self.object:
            context["bids"] = self.object.bids
        return context


class UserEditView(LoginRequiredMixin, UpdateView):
    """View for editing user information."""

    template_name = "users/profile_edit.html"
    form_class = forms.UserEditForm
    success_url = reverse_lazy("users:login")

    def get_object(self, queryset=None):
        """Get user object from request."""
        return self.request.user

templates/users/change_password.html
{% extends 'users/form.html' %}
{% load i18n %}

{% block title %}
  {% trans "Password change" %}
{% endblock %}

{% block form-title %}
  {% trans "Changing password" %}
{% endblock %}

templates/users/form.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}


{% block content %}
  <form class="row p-2" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <h1 class="col-12 mb-4 text-center">
      {% block form-title %}
      {% endblock %}
    </h1>
    <div class="col-6 offset-3">
      {{ form|crispy }}
    </div>
    {% block additional_content %}
    {% endblock %}
    <input type="submit" value="{% trans 'Submit' %}" class="btn bg-gradient-primary col-2 offset-5">
  </form>
{% endblock %}

templates/users/login.html
{% extends 'users/form.html' %}
{% load i18n %}

{% block title %}
  {% trans "Login" %}
{% endblock %}

{% block form-title %}
  {% trans "Log in system" %}
{% endblock %}

{% block additional_content %}
  <a href="{% url 'users:reset-password' %}" class="col-4 offset-4 mb-2 text-center">
    {% trans "Forgot password?" %}
  </a>
  <a href="{% url 'users:registration' %}" class="col-4 offset-4 mb-2 text-center">
    {% trans "Don't have an account?" %}
  </a>
{% endblock %}

templates/users/profile_edit.html
{% extends 'users/form.html' %}
{% load i18n %}

{% block title %}
  {% trans "Editing" %} {{ user.email }} {% trans "profile" %}
{% endblock %}

{% block form-title %}
  {% trans "Editing" %} {{ user.email }} {% trans "profile" %}
{% endblock %}

templates/users/registration.html
{% extends 'users/form.html' %}
{% load i18n %}

{% block title %}
  {% trans "Registration" %}
{% endblock %}

{% block form-title %}
  {% trans "Registration" %}
{% endblock %}

templates/users/reset_password.html
{% extends 'users/form.html' %}
{% load i18n %}

{% block title %}
  {% trans "Password reset" %}
{% endblock %}

{% block form-title %}
  {% trans "Reseting password" %}
{% endblock %}

templates/users/reset_password_complete.html
{% extends 'users/reset_password.html' %}
{% load i18n %}

{% block additional_content %}
{% if not validlink %}
  <div class="alert alert-danger mt-4 text-center">
    <h3>{% trans "Invalid link" %}</h3>
  </div>
{% endif %}
{% endblock %}

templates/users/success.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
  {% trans 'Success' %}
{% endblock %}

{% block content %}
  <div class="p-3 text-center">
    <h2>{{ title }}</h2>
  </div>
{% endblock %}

templates/users/user_detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
Profile User
{% endblock %}

{% block stylesheets %}
  <style>
    th > a {
      letter-spacing: 0;
      color: #67748e;
    }
    
    #lost-container {
      max-height: {% if request.user == user %}33vh{% else %}60vh{% endif %};
    }

    #bids-container {
      max-height: 30vh;
    }
  </style>
{% endblock stylesheets %}

{% block content %}
<div class="row p-2">
  <div class="col-3">
    <img class="img-thumbnail mt-2" src="
    {% if user.avatar %}
      {{ user.avatar.url }}
    {% endif %}
    "/>
    <span class="d-block fs-2 m-2">{{ user.first_name }} {{ user.last_name }}</span>
    <span class="text-muted fs-5 m-2 ms-4">{{ user.email }}</span>
  </div>
  <div class="col-9">
    <div class="position-relative container-fluid p-0">
      <h3 class="col-12 text-center my-2 mx-0">Username lots</h3>
      {% if request.user == user %}
        <a href="{% url 'lots:create' %}" class="position-absolute top-0 end-0 mt-2 me-5 py-1 px-4 btn bg-gradient-success">Add lot</a>
      {% endif %}
      <div class="row overflow-auto" id="lost-container">
        {% if lots %}
          {% for item in lots.all %}
            <div class="row my-1">
              <a href="{% url 'lots:details' item.pk %}" class="col-2">
                {% with preview=item.images.all|first %}
                  <img src="{{ preview.image.url }}" class="img-thumbnail">
                {% endwith %}
              </a>
              <div class="col-6">
                <span class="d-block fs-5">{{ item.name }}</span>
                <span>{{ item.description }}</span>
              </div>
              <div class="col-4 d-flex flex-column justify-content-evenly">
                {% if item.status == "DRAFT" %}
                  <a class="col-4 btn ms-auto" href="{% url 'lots:update' item.pk %}">
                    Edit
                  </a>
                {% endif %}
                <div class="col-12 text-end">
                  {% if item.status == "DRAFT" %}
                    <span class="badge bg-light">{{ item.get_status_display }}</span>
                  {% elif item.status == "IN_PROCCESS" %}
                    <span class="badge bg-success">{{ item.get_status_display }}</span>
                  {% elif item.status == "FINISHED" %}
                    <span class="badge bg-secondary">{{ item.get_status_display }}</span>
                  {% endif %}
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
            <p class="col text-center">{% trans "Nothing found" %}</p>
        {% endif %}
      </div>
      <br>
      {% if request.user == user %}
        <h3 class="col-12 text-center my-2 mx-0">Username bids</h3>
        <div class="container-fluid overflow-auto" id="bids-container">
          <table class="table table-hover">
            {% if bids %}
              <thead>
                <tr>
                  <th scope="col" class="fs-4 px-1">Lot Name</th>
                  <th scope="col" class="fs-4 px-1">Bid amount</th>
                  <th scope="col" class="fs-4 px-1">Bid time</th>
                </tr>
              </thead>
              <tbody>
                {% for item in bids.all %}
                  <tr {% if item != item.lot.bids.all|first %}class="alert alert-danger"{% endif %}>
                    <th scope="row"><a href="{% url 'lots:details' item.lot.pk %}">{{ item.lot.name }}</a></th>
                    <th>{{ item.bid }}</th>
                    <th>{{ item.created }}</th>
                  </tr>
                {% endfor %}
              </tbody>
            {% else %}
                <p class="col text-center">{% trans "Nothing found" %}</p>
            {% endif %}
          </table>
        </div>
      {% endif %}
    </div>
    <div class="container-fluid">
    </div>
  </div>
</div>
{% endblock %}